on: push

jobs:
  push_and_restart_bot_alwaysdata:
    name: Pull and restart
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: if git diff --exit-code requirements.txt; then git pull && pip install -r requirements.txt; else git pull; fi
      - name: Restart bot using curl API request
        run: "curl -X POST --basic --user ${{ secrets.API_KEY }}: https://api.alwaysdata.com/v1/service/${{ secrets.SERVICE_ID }}/restart/"
